import 'package:flutter/material.dart';
// import '../rust/api/wallet.dart'; // Will be generated by flutter_rust_bridge

class WalletProvider extends ChangeNotifier {
  String? _walletAddress;
  double _balance = 0.0;
  bool _isConnected = false;
  bool _isLoading = false;
  String? _error;

  String? get walletAddress => _walletAddress;
  double get balance => _balance;
  bool get isConnected => _isConnected;
  bool get isLoading => _isLoading;
  String? get error => _error;

  Future<void> createWallet() async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      // TODO: Call Rust function via flutter_rust_bridge
      // final wallet = await createWallet();

      // Placeholder implementation
      await Future.delayed(const Duration(seconds: 1));
      _walletAddress = 'addr1_placeholder_new_wallet';
      _balance = 0.0;
      _isConnected = true;
    } catch (e) {
      _error = e.toString();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> restoreWallet(List<String> recoveryPhrase) async {
    _isLoading = true;
    _error = null;
    notifyListeners();

    try {
      // TODO: Call Rust function
      // final wallet = await restoreWalletFromPhrase(phrase: recoveryPhrase);

      await Future.delayed(const Duration(seconds: 1));
      _walletAddress = 'addr1_placeholder_restored_wallet';
      _balance = 10.5;
      _isConnected = true;
    } catch (e) {
      _error = e.toString();
    } finally {
      _isLoading = false;
      notifyListeners();
    }
  }

  Future<void> refreshBalance() async {
    if (!_isConnected || _walletAddress == null) return;

    try {
      // TODO: Call Rust function
      // final balance = await getWalletBalance(address: _walletAddress!);

      await Future.delayed(const Duration(milliseconds: 500));
      _balance = 10.5; // Placeholder
      notifyListeners();
    } catch (e) {
      _error = e.toString();
      notifyListeners();
    }
  }

  void disconnectWallet() {
    _walletAddress = null;
    _balance = 0.0;
    _isConnected = false;
    _error = null;
    notifyListeners();
  }
}
