name: pinwout_vc
description: "Power In, Work Out."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  heroicons: ^0.11.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  confetti: ^0.8.0
  firebase_analytics: ^11.4.5
  firebase_storage: ^12.4.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
